# Generated by Django 5.0.6 on 2024-07-02 17:32

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("expected_return_date__gte", models.F("borrow_date")),
                    ("actual_return_date__gte", models.F("borrow_date")),
                ),
                name="return_date_gte_borrow_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "expected_return_date__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("borrow_date"),
                            "+",
                            models.Value(datetime.timedelta(days=14)),
                        ),
                    )
                ),
                name="expected_return_date_within_two_weeks",
            ),
        ),
    ]
